### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sweetclimusic** [eospi/RealityKit-Instrument-Zoo#1]
Hi Great tutorial. 

I followed along and learned a lot about realitykit. I lasted try ARKit in version 2.  I have two issues I wanted you to help with.
The first is more a usdz issue.  sketchfab now supports export to usdz, so I downloaded the following file to add a fourth instrument. 

Credit for Djembe Drum, Djembe Goplet Drum - by aqpetteri - https://sketchfab.com/3d-models/djembe-goplet-drum-572d364642434810abd1fa7cfb6e7782 

In Xcode i set the scale to 0.1,0.1,0.1  on its local space as it's huge.  It fits in the scene with the other instruments. However it moves after the animations ends.  (up and towards camera). How do I address this issue? I suspect it will happen frequently if I am importing models from the web.

The next issue I had was a question. I have a loading animation playing when the models are being loaded. I would like to continue playing the animation until the objects are placed in the scene. Is there an event I can subscribe to end my animation when objects appear?  I couldn't find anything, I tried SceneEvents.AnchoredStateChanged.self but this is fired a lot and crashes a second time at  `anchorCancellable?.cancel()`
```swift
//MARK: I want to know when my objects are visible.
   var anchorCancellable: Cancellable? = nil
       anchorCancellable = arView.scene.subscribe(to: SceneEvents.AnchoredStateChanged.self, on: anchor) {
          (event) in
              if event.isAnchored && anchor.children.count == 4 {
                  anchorCancellable?.cancel()
                  self.loading = false
                  self.controlLoadingAnimation()
            }
        }
```

The reason I still want the animation to play is I've been testing in a busy room and it takes a while to find a plane to place objects on ( I think that's what's happening)

Again thanks for the tutorial.

**Comment by eospi** [comment]
Thank you, I'm glad you found it helpful! 

The moving is likely due to the model not being at the center of its coordinate system. Are you scaling with the `setSize(relativeTo:)` method? I just looked at the code and noticed it doesn't actually use the reference entity and always sets it to `nil`. I'll get that fixed, and hopefully that will solve your issue. This is what the method should look like so you can try it out.

```swift
extension Entity {
    func setSize(_ size: Float, relativeTo entity: Entity?) {
        let currentSize = self.visualBounds(recursive: true, relativeTo: entity, excludeInactive: false).extents.max()
        let scaleFactor = size / currentSize
        setScale([scaleFactor, scaleFactor, scaleFactor], relativeTo: entity)
    }
}
```

For your second question, `SceneEvents.AnchoredStateChanged` should run every time ARKit updates the plane, which it continually refines as it receives more information about the scene. To only stop the animation when the plane first appears, you could store a property called `foundPlane` in your view controller, initially set to `false`. Set it `event.isAnchored` every time the event runs, and when it changes to `true` for the first time, your objects should now be showing. 

I think you should be able to leave out `anchorCancellable?.cancel()` for scene subscriptions, so hopefully that will resolve the crash.

Let me know if this works!

**Comment by sweetclimusic** [comment]
How do I verify this?
>
> center of its coordinate system


I noticed the issue with the setScale relativeTo always being nil as well.


So I thought the event.isAnchored would work, which is my sample code I
sent over. But once it is "anchored" there still aren't any objects in the
scene. This might be my room issue, where I am in a very noisy
environment and no clear "Floor". So I stop the loading animation on
event.isAnchored but there won't be any models in the scene for sometime as
I move around.  Which is why I wondered if there was an event for a
ModelEntity appearing?

**Comment by sweetclimusic** [comment]
The model under the drum.FBX root node has an offset on it's Y. So if I
zero this out on the usdz and adjust on the Y in code when reality
kit loads the model instead?

**Comment by eospi** [comment]
I believe changing the Y offset should fix that problem! If not, changing the reference entity to `self` might help.

If the event.isAnchored isn't working as expected, you could implement plane detection with the `ARSessionDelegate` instead of letting RealityKit handle it automatically. You can check for an `ARPlaneAnchor` on the method `session(_:didAdd:)` and add an `AnchorEntity` at its transform. Here is the Apple Documentation for that method: https://developer.apple.com/documentation/arkit/arsessiondelegate/2865617-session.

**Comment by sweetclimusic** [comment]
Hi Ethan,

In the end I just reset the translation to zero in the scale as you have
done in the shrink. This prevented the object from moving. I didn't try to
reference the entity self.  I also haven't tried managing the session
myself. ( something for another project)

But I did have a higher level ARKit/Realitykit question you might be able
to answer. ( offtopic to this issue).

If I wanted to do cloth physics, is that possible? Right now I'm thinking
the only real way to do it is to create a Unity project that does the cloth
physics and "continue" the coding in Xcode. I'm wanting to create a physics
experience with ropes and nets.

Thanks

**Comment by eospi** [comment]
I’m glad you fixed the moving issue! Working with meshes directly in RealityKit is currently very limited. However, you can design the animations in a 3D modeling app like Blender and save them in your USDZ file. In Xcode, you just play the animation you want in RealityKit code. If Unity can export to USDZ, then that will be perfect!
